version: '3.9'

services:
  backend:
    build: ./backend
    container_name: "adobe-task-backend"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./backend/logs:/backend/logs

  frontend:
    build: ./frontend/adobe-task-frontend
    container_name: "adobe-task-frontend"
    ports:
      - "3000:80"
    restart: always
