version: '3.9'

services:
  backend:
    build: ./backend
    container_name: "adobe-task-backend"
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
    restart: always
    volumes:
      - ./backend/logs:/backend/logs

  jaeger:
    image: jaegertracing/all-in-one:1.45
    ports:
      - "16686:16686"
      - "14268:14268"

  frontend:
    build: ./frontend/adobe-task-frontend
    container_name: "adobe-task-frontend"
    ports:
      - "3000:80"
    restart: always
